package com.example.querynest.parser.lexer;

public enum TokenType {
    CREATE, TABLE, PRIMARY, KEY, FOREIGN, REFERENCES, UNIQUE,
    NOT, NULL, DEFAULT, CONSTRAINT, ORDER, BY,

    VARCHAR, INTEGER, BIGINT, BOOLEAN, DATE, TIMESTAMP, DECIMAL, TEXT,

    LEFT_PAREN, RIGHT_PAREN, COMMA, SEMICOLON,

    IDENTIFIER, NUMBER, STRING,

    EOF, UNKNOWN
}