package com.example.querynest.parser.lexer;

public enum TokenType {
    CREATE, TABLE, PRIMARY, KEY, FOREIGN, REFERENCES, UNIQUE,
    NOT, NULL, DEFAULT, CONSTRAINT, ORDER, BY,
    ENGINE,
    EQUAL,
    VARCHAR, INTEGER, BIGINT, BOOLEAN, DATE, TIMESTAMP, DECIMAL, TEXT,

    LEFT_PAREN, RIGHT_PAREN, COMMA, SEMICOLON,

    IDENTIFIER, NUMBER, STRING,

    EOF, UNKNOWN,
    SELECT, FROM, WHERE, LIMIT,
    AND, OR,
    STAR,
    NOT_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL
}
